### ISSUE TITLE
Plasma file extension clashes with P Language

### ISSUE THREAD

**Issue by AurumByte** [PlasmaLang/plasma#351]
Currently, Plasma and P have the same file extension ( .p ). This may not seem like an issue, but if one of the two languages decide to add GitHub support, the other language will have problems.

refer [P Lang wiki](https://github.com/p-org/P/wiki) for more info.

**Comment by PaulBone** [comment]
This is not a bug in Plasma.

This issue about verious letters of the alphabet has come up in the past with github.

I ran into this in 2014 when I [attempted to add Mercury support to linguist](https://github.com/github/linguist/pull/748), but github refused to merge this for some time because they had engineerd linguist to assume that only one language can use a single file extension.  Despite this being blatently untrue when Mercury, MUMPS, Objective-C and Matlab all share `.m`, Prolog and Perl share `.pl` and many C-dialect languages (C, C++, Objective-C).

Finally a contributor [fixed the problem](https://github.com/github/linguist/pull/985) in linguist to remove this assumption. I'd be surprised that after this Github enginners still assume that two languages cannot share the same file extension, this shouldn't be a problem for Plasma and P.  This is not a bug in either Plasma or P.

**Comment by ACleverDisguise** [comment]
I see Github is back at being rodeo clowns.

**Comment by ACleverDisguise** [comment]
> Currently, Plasma and P have the same file extension ( .p ). This may not seem like an issue, but if one of the two languages decide to add GitHub support, the other language will have problems.
> 
> refer [P Lang wiki](https://github.com/p-org/P/wiki) for more info.

You realize that .p was used for Pascal before either Plasma or P were even a gleam in the mailman's eye, right?  There's a certain degree of offputting arrogance at work here for the creator of one language to send people off to the repository of another language demanding a change to file extensions.  It makes me think far less of P's creator that this has happened.

**Comment by AurumByte** [comment]
Actually, I take an interest in the working of programming languages and didn't know that multiple languages can have the same extension. Every repo/language/implementation had a unique extension and so my so-called "percieving of programming languages". Also, I am in no way a creator/maintainer/contributor to P. I just thought that I could help by pointing this out.

**Comment by ACleverDisguise** [comment]
> Actually, I take an interest in the working of programming languages and didn't know that multiple languages can have the same extension. Every repo/language/implementation had a unique extension and so my so-called "percieving of programming languages". Also, I am in no way a creator/maintainer/contributor to P. I just thought that I could help by pointing this out.

Well, peruse that link I put up then.  There's a LOT of file extension clashes because, well, there's only 26 letters in the English alphabet.  Since, courtesy of intense conservatism in programming circles, we're never likely to see a language with the extension, say, .笨, we're stuck with clashes in naming and Github screwing up its Linguist library as usual.

**Comment by AurumByte** [comment]
OK. I am still kinda new here so I still have to get used to how stuff work around here.
